apiVersion: updatebot.jenkins-x.io/v1alpha1
kind: UpdateConfig
spec:
  rules:
    - urls:
        - https://github.com/jenkins-x/jx3-versions
      changes:
        - regex:
            pattern: version:\s(.*)
            files:
              - "git/github.com/jenkins-x/terraform-aws-eks-jx.yml"
